# Generated by Django 3.1.4 on 2020-12-16 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Table_ID', models.TextField()),
                ('Sourcing_competitor', models.TextField()),
                ('Common_sources', models.TextField()),
                ('Restaurant_name', models.TextField()),
                ('Tags', models.TextField()),
                ('Average_basket_value', models.TextField()),
                ('Country', models.TextField()),
                ('City_code', models.TextField()),
                ('Address', models.TextField()),
                ('Latitude', models.TextField()),
                ('Longitude', models.TextField()),
                ('Phone_number', models.TextField()),
                ('Rating', models.TextField()),
                ('Number_of_reviews', models.TextField()),
                ('Website', models.TextField()),
                ('URL', models.TextField()),
                ('Postal_code', models.TextField()),
                ('Place_ID', models.TextField()),
                ('user_ratings_total', models.TextField()),
                ('google_grade', models.TextField()),
            ],
        ),
    ]
